### ISSUE TITLE
Error result in Turbobfs

### ISSUE THREAD

**Issue by iosmers** [pcdslab/TurboBFS#1]
Hi, I run Turbobfs `./run_bfstdcsc.sh`, but I get some error result. why?

mycielskian4
TurboBFS_CSC_TD nvprof --profile-api-trace none ./exec /home/hustgpu/TurboBFS/graphData/mycielskian4.mtx --w 0 --ug 1 --format 1 --p 1 --r 0 --repet 1 --seq 1

N = 11,M = 11, nz = 40
maximum degree = 5 of node = 10
degree statistics:meanDegree=  3.64,sdDegree =   0.67,
Degree 0: 0 (0.000 %)
Degree 2^0: 0 (0.000 %))
Degree 2^1: 5 (45.455 %))
Degree 2^2: 6 (54.545 %))

bfs_seq_ug_csc::d = 3,r = 0
bfstdcsc_seq::f <-- f +sigma time = 0.000003s
bfstdcsc_seq::f_t <-- fA time = 0.000039s
bfstdcsc_seq::f <-- f_t time = 0.000039s
bfstdcsc_seq::f <-- f*(-sigma) time = 0.000001s
bfstdcsc_seq::S vector time = 0.000001s
bfstdcsc_seq::c <-- check (f=0)) time = 0.000002s
bfstdcsc_seq::sequential top-down BFS total time = 0.000085s
bfs td seq CSC time = 0.000694s
==13154== NVPROF is profiling process 13154, command: ./exec /home/hustgpu/TurboBFS/graphData/mycielskian4.mtx 0 1 1 1 0 1 1

bfsgputdcsc_wa::d = 1,r = 0,t_sum=0.309056ms
bfsgputdcsc_wa::time f <-- fA = 0.222336ms
bfsgputdcsc_wa::time time bfs functions = 0.086720ms
bfsgputdcsc_wa::average time BFS  = 0.309056ms

** check sigma in CSC(wa) format: error in 11 values of the GPU computed sigma_hgpu vector**

**check values of S_hgpu: error in 10 values of the GPU computed S_hgpu vector**

visited vertices == 0

S   S_hgpu
0,0,0
1,1,0
2,2,0
3,1,0
4,2,0
5,2,0
6,1,0
7,2,0
8,1,0
9,2,0
10,2,0

sigma   sigma_hgpu
0,1.000000,0.000000
1,1.000000,0.000000
2,2.000000,0.000000
3,1.000000,0.000000
4,2.000000,0.000000
5,2.000000,0.000000
6,1.000000,0.000000
7,1.000000,0.000000
8,1.000000,0.000000
9,1.000000,0.000000
10,2.000000,0.000000

scan=0.000s,degree_t= 0.000s,transf_format_t=0.000s,bfs_td_seq_t=0.001s
==13154== Profiling application: ./exec /home/hustgpu/TurboBFS/graphData/mycielskian4.mtx 0 1 1 1 0 1 1
==13154== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   58.14%  9.0240us         4  2.2560us  1.8880us  2.8480us  [CUDA memset]
                   25.77%  4.0000us         2  2.0000us  1.8880us  2.1120us  [CUDA memcpy DtoH]
                   16.08%  2.4960us         2  1.2480us     960ns  1.5360us  [CUDA memcpy HtoD]
No API activities were profiled.

==13154== Unified Memory profiling result:
Device "Tesla K40c (0)"
   Count  Avg Size  Min Size  Max Size  Total Size  Total Time  Name
       2  32.000KB  4.0000KB  60.000KB  64.00000KB  9.536000us  Device To Host
Total CPU Page faults: 1
Tina_AskCal
TurboBFS_CSC_TD nvprof --profile-api-trace none ./exec /home/hustgpu/TurboBFS/graphData/Tina_AskCal.mtx --w 0 --ug 0 --format 0 --p 1 --r 10 --repet 1 --seq 1

N = 11,M = 11, nz = 29
maximum in_degree = 7 of node = 1
maximum out_degree = 5 of node = 2
degree statistics:meanInDegree=  2.64,sdInDegree =   2.11,
degree statistics:meanOutDegree=  2.64,sdOutDegree =   1.21,
accumulated in-degree distribution
Degree 0: 1 (9.091 %)
Degree 2^0: 3 (27.273 %))
Degree 2^1: 3 (27.273 %))
Degree 2^2: 4 (36.364 %))

accumulated out-degree distribution
Degree 0: 0 (0.000 %)
Degree 2^0: 2 (18.182 %))
Degree 2^1: 7 (63.636 %))
Degree 2^2: 2 (18.182 %))

bfs_seq_ug_csc::d = 3,r = 10
bfstdcsc_seq::f <-- f +sigma time = 0.000002s
bfstdcsc_seq::f_t <-- fA time = 0.000130s
bfstdcsc_seq::f <-- f_t time = 0.000003s
bfstdcsc_seq::f <-- f*(-sigma) time = 0.000003s
bfstdcsc_seq::S vector time = 0.000003s
bfstdcsc_seq::c <-- check (f=0)) time = 0.000034s
bfstdcsc_seq::sequential top-down BFS total time = 0.000175s
bfs td seq CSC time = 0.000907s
==13168== NVPROF is profiling process 13168, command: ./exec /home/hustgpu/TurboBFS/graphData/Tina_AskCal.mtx 0 0 0 1 10 1 1

bfsgputdcsc_sc::d = 1,r = 10,t_sum=0.028704ms
bfsgputdcsc_sc::time f <-- fA d = 0.021408ms
bfsgputdcsc_sc::time time bfs functions d = 0.007296ms
bfsgputdcsc_sc::average time BFS d = 0.028704ms

**check sigma in CSC(sc) format: error in 7 values of the GPU computed sigma_hgpu vector**

**check values of S_hgpu: error in 6 values of the GPU computed S_hgpu vector**

visited vertices == 0

S   S_hgpu
0,2,0
1,2,0
2,1,0
3,2,0
4,0,0
5,1,0
6,0,0
7,1,0
8,0,0
9,0,0
10,0,0

sigma   sigma_hgpu
0,1.000000,0.000000
1,3.000000,0.000000
2,1.000000,0.000000
3,2.000000,0.000000
4,0.000000,0.000000
5,1.000000,0.000000
6,0.000000,0.000000
7,1.000000,0.000000
8,0.000000,0.000000
9,0.000000,0.000000
10,1.000000,0.000000

scan=0.000s,degree_t= 0.000s,transf_format_t=0.000s,bfs_td_seq_t=0.001s
==13168== Profiling application: ./exec /home/hustgpu/TurboBFS/graphData/Tina_AskCal.mtx 0 0 0 1 10 1 1
==13168== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   52.31%  6.8800us         3  2.2930us  1.9200us  2.8160us  [CUDA memset]
                   28.95%  3.8080us         2  1.9040us  1.6960us  2.1120us  [CUDA memcpy DtoH]
                   18.73%  2.4640us         2  1.2320us     928ns  1.5360us  [CUDA memcpy HtoD]
No API activities were profiled.

==13168== Unified Memory profiling result:
Device "Tesla K40c (0)"
   Count  Avg Size  Min Size  Max Size  Total Size  Total Time  Name
       2  32.000KB  4.0000KB  60.000KB  64.00000KB  9.504000us  Device To Host
Total CPU Page faults: 1
Ragusa18
TurboBFS_CSC_TD nvprof --profile-api-trace none ./exec /home/hustgpu/TurboBFS/graphData/Ragusa18.mtx --w 1 --ug 0 --format 0 --p 1 --r 0 --repet 10 --seq 1

N = 23,M = 23, nz = 64
maximum in_degree = 12 of node = 20
maximum out_degree = 7 of node = 10
degree statistics:meanInDegree=  2.78,sdInDegree =   3.13,
degree statistics:meanOutDegree=  2.78,sdOutDegree =   2.00,
accumulated in-degree distribution
Degree 0: 5 (21.739 %)
Degree 2^0: 5 (21.739 %))
Degree 2^1: 7 (30.435 %))
Degree 2^2: 4 (17.391 %))
Degree 2^3: 2 (8.696 %))

accumulated out-degree distribution
Degree 0: 2 (8.696 %)
Degree 2^0: 7 (30.435 %))
Degree 2^1: 5 (21.739 %))
Degree 2^2: 9 (39.130 %))

bfs_seq_ug_csc::d = 5,r = 0
bfstdcsc_seq::f <-- f +sigma time = 0.000004s
bfstdcsc_seq::f_t <-- fA time = 0.000153s
bfstdcsc_seq::f <-- f_t time = 0.000041s
bfstdcsc_seq::f <-- f*(-sigma) time = 0.000004s
bfstdcsc_seq::S vector time = 0.000003s
bfstdcsc_seq::c <-- check (f=0)) time = 0.000004s
bfstdcsc_seq::sequential top-down BFS total time = 0.000208s
bfs td seq CSC time = 0.000871s
==13179== NVPROF is profiling process 13179, command: ./exec /home/hustgpu/TurboBFS/graphData/Ragusa18.mtx 1 0 0 1 0 10 1

bfsgputdcsc_sc::d = 1,r = 0,t_sum=1.884896ms
bfsgputdcsc_sc::time f <-- fA d = 0.106573ms
bfsgputdcsc_sc::time time bfs functions d = 0.081917ms
bfsgputdcsc_sc::average time BFS d = 0.188490ms

**check sigma in CSC(sc) format: error in 18 values of the GPU computed sigma_hgpu vector**

**Comment by OswArti** [comment]
Hi: You should check your GPU since it is not computing the expected results. I just run the same code and here are the results. Thanks for using TurboBFS:
mycielskian4
TurboBFS_CSC_TD ./exec /lclhome/oarti001/documents/cuBFS/TurboBFS-git/TurboBFS/graphData/mycielskian4.mtx --w 0 --ug 1 --format 1 --p 1 --r 0 --repet 1 --seq 1

N = 11,M = 11, nz = 40
maximum degree = 5 of node = 10
degree statistics:meanDegree=  3.64,sdDegree =   0.67,
Degree 0: 0 (0.000 %)
Degree 2^0: 0 (0.000 %))
Degree 2^1: 5 (45.455 %))
Degree 2^2: 6 (54.545 %))

bfs_seq_ug_csc::d = 3,r = 0 
bfstdcsc_seq::f <-- f +sigma time = 0.000001s 
bfstdcsc_seq::f_t <-- fA time = 0.000003s 
bfstdcsc_seq::f <-- f_t time = 0.000001s 
bfstdcsc_seq::f <-- f*(-sigma) time = 0.000001s 
bfstdcsc_seq::S vector time = 0.000002s 
bfstdcsc_seq::c <-- check (f=0)) time = 0.000000s 
bfstdcsc_seq::sequential top-down BFS total time = 0.000008s 
bfs td seq CSC time = 0.000083s

bfsgputdcsc_wa::d = 3,r = 0,t_sum=0.741760ms 
bfsgputdcsc_wa::time f <-- fA = 0.047520ms 
bfsgputdcsc_wa::time time bfs functions = 0.694240ms 
bfsgputdcsc_wa::average time BFS  = 0.741760ms 

check sigma in CSC(wa) format: values of the GPU computed sigma vector are correct 

check values of S_hgpu: values of the GPU computed S vector are correct 

visited vertices == 11

S   S_hgpu 
0,0,0
1,1,1
2,2,2
3,1,1
4,2,2
5,2,2
6,1,1
7,2,2
8,1,1
9,2,2
10,2,2

sigma   sigma_hgpu 
0,1.000000,1.000000
1,1.000000,1.000000
2,2.000000,2.000000
3,1.000000,1.000000
4,2.000000,2.000000
5,2.000000,2.000000
6,1.000000,1.000000
7,1.000000,1.000000
8,1.000000,1.000000
9,1.000000,1.000000
10,2.000000,2.000000

scan=0.000s,degree_t= 0.000s,transf_format_t=0.000s,bfs_td_seq_t=0.000s
Tina_AskCal
TurboBFS_CSC_TD ./exec /lclhome/oarti001/documents/cuBFS/TurboBFS-git/TurboBFS/graphData/Tina_AskCal.mtx --w 0 --ug 0 --format 0 --p 1 --r 10 --repet 1 --seq 1

N = 11,M = 11, nz = 29
maximum in_degree = 7 of node = 1
maximum out_degree = 5 of node = 2
degree statistics:meanInDegree=  2.64,sdInDegree =   2.11,
degree statistics:meanOutDegree=  2.64,sdOutDegree =   1.21,
accumulated in-degree distribution
Degree 0: 1 (9.091 %)
Degree 2^0: 3 (27.273 %))
Degree 2^1: 3 (27.273 %))
Degree 2^2: 4 (36.364 %))

accumulated out-degree distribution
Degree 0: 0 (0.000 %)
Degree 2^0: 2 (18.182 %))
Degree 2^1: 7 (63.636 %))
Degree 2^2: 2 (18.182 %))

bfs_seq_ug_csc::d = 3,r = 10 
bfstdcsc_seq::f <-- f +sigma time = 0.000002s 
bfstdcsc_seq::f_t <-- fA time = 0.000002s 
bfstdcsc_seq::f <-- f_t time = 0.000001s 
bfstdcsc_seq::f <-- f*(-sigma) time = 0.000000s 
bfstdcsc_seq::S vector time = 0.000001s 
bfstdcsc_seq::c <-- check (f=0)) time = 0.000000s 
bfstdcsc_seq::sequential top-down BFS total time = 0.000006s 
bfs td seq CSC time = 0.000082s

bfsgputdcsc_sc::d = 3,r = 10,t_sum=0.583456ms 
bfsgputdcsc_sc::time f <-- fA d = 0.036992ms 
bfsgputdcsc_sc::time time bfs functions d = 0.546464ms 
bfsgputdcsc_sc::average time BFS d = 0.583456ms 

check sigma in CSC(sc) format: values of the GPU computed sigma vector are correct 

check values of S_hgpu: values of the GPU computed S vector are correct 

visited vertices == 7

S   S_hgpu 
0,2,2
1,2,2
2,1,1
3,2,2
4,0,0
5,1,1
6,0,0
7,1,1
8,0,0
9,0,0
10,0,0

sigma   sigma_hgpu 
0,1.000000,1.000000
1,3.000000,3.000000
2,1.000000,1.000000
3,2.000000,2.000000
4,0.000000,0.000000
5,1.000000,1.000000
6,0.000000,0.000000
7,1.000000,1.000000
8,0.000000,0.000000
9,0.000000,0.000000
10,1.000000,1.000000

scan=0.000s,degree_t= 0.000s,transf_format_t=0.000s,bfs_td_seq_t=0.000s
Ragusa18
TurboBFS_CSC_TD ./exec /lclhome/oarti001/documents/cuBFS/TurboBFS-git/TurboBFS/graphData/Ragusa18.mtx --w 1 --ug 0 --format 0 --p 1 --r 0 --repet 10 --seq 1

N = 23,M = 23, nz = 64
maximum in_degree = 12 of node = 20
maximum out_degree = 7 of node = 10
degree statistics:meanInDegree=  2.78,sdInDegree =   3.13,
degree statistics:meanOutDegree=  2.78,sdOutDegree =   2.00,
accumulated in-degree distribution
Degree 0: 5 (21.739 %)
Degree 2^0: 5 (21.739 %))
Degree 2^1: 7 (30.435 %))
Degree 2^2: 4 (17.391 %))
Degree 2^3: 2 (8.696 %))

accumulated out-degree distribution
Degree 0: 2 (8.696 %)
Degree 2^0: 7 (30.435 %))
Degree 2^1: 5 (21.739 %))
Degree 2^2: 9 (39.130 %))

bfs_seq_ug_csc::d = 5,r = 0 
bfstdcsc_seq::f <-- f +sigma time = 0.000002s 
bfstdcsc_seq::f_t <-- fA time = 0.000006s 
bfstdcsc_seq::f <-- f_t time = 0.000000s 
bfstdcsc_seq::f <-- f*(-sigma) time = 0.000004s 
bfstdcsc_seq::S vector time = 0.000001s 
bfstdcsc_seq::c <-- check (f=0)) time = 0.000000s 
bfstdcsc_seq::sequential top-down BFS total time = 0.000013s 
bfs td seq CSC time = 0.000094s

bfsgputdcsc_sc::d = 5,r = 0,t_sum=5.735232ms 
bfsgputdcsc_sc::time f <-- fA d = 0.049139ms 
bfsgputdcsc_sc::time time bfs functions d = 0.524384ms 
bfsgputdcsc_sc::average time BFS d = 0.573523ms 

check sigma in CSC(sc) format: values of the GPU computed sigma vector are correct 

check values of S_hgpu: values of the GPU computed S vector are correct 

visited vertices == 18

S   S_hgpu 
0,0,0
1,2,2
2,2,2
3,0,0
4,0,0
5,4,4
6,3,3
7,4,4
8,3,3
9,4,4
10,2,2
11,3,3
12,3,3
13,4,4
14,0,0
15,4,4
16,0,0
17,0,0
18,4,4
19,2,2
20,1,1
21,3,3
22,2,2

sigma   sigma_hgpu 
0,1.000000,1.000000
1,1.000000,1.000000
2,1.000000,1.000000
3,0.000000,0.000000
4,0.000000,0.000000
5,2.000000,2.000000
6,1.000000,1.000000
7,1.000000,1.000000
8,1.000000,1.000000
9,1.000000,1.000000
10,1.000000,1.000000
11,1.000000,1.000000
12,1.000000,1.000000
13,1.000000,1.000000
14,0.000000,0.000000
15,1.000000,1.000000
16,0.000000,0.000000
17,0.000000,0.000000
18,1.000000,1.000000
19,1.000000,1.000000
20,1.000000,1.000000
21,1.000000,1.000000
22,1.000000,1.000000

scan=0.000s,degree_t= 0.000s,transf_format_t=0.000s,bfs_td_seq_t=0.000s
cage4
TurboBFS_CSC_TD ./exec /lclhome/oarti001/documents/cuBFS/TurboBFS-git/TurboBFS/graphData/cage4.mtx --w 1 --ug 0 --format 0 --p 1 --r 0 --repet 10 --seq 1

N = 9,M = 9, nz = 49
maximum in_degree = 6 of node = 4
maximum out_degree = 6 of node = 4
degree statistics:meanInDegree=  5.44,sdInDegree =   0.53,
degree statistics:meanOutDegree=  5.44,sdOutDegree =   0.53,
accumulated in-degree distribution
Degree 0: 0 (0.000 %)
Degree 2^0: 0 (0.000 %))
Degree 2^1: 0 (0.000 %))
Degree 2^2: 9 (100.000 %))

accumulated out-degree distribution
Degree 0: 0 (0.000 %)
Degree 2^0: 0 (0.000 %))
Degree 2^1: 0 (0.000 %))
Degree 2^2: 9 (100.000 %))

bfs_seq_ug_csc::d = 3,r = 0 
bfstdcsc_seq::f <-- f +sigma time = 0.000002s 
bfstdcsc_seq::f_t <-- fA time = 0.000002s 
bfstdcsc_seq::f <-- f_t time = 0.000001s 
bfstdcsc_seq::f <-- f*(-sigma) time = 0.000000s 
bfstdcsc_seq::S vector time = 0.000000s 
bfstdcsc_seq::c <-- check (f=0)) time = 0.000001s 
bfstdcsc_seq::sequential top-down BFS total time = 0.000006s 
bfs td seq CSC time = 0.000084s

bfsgputdcsc_sc::d = 3,r = 0,t_sum=3.701952ms 
bfsgputdcsc_sc::time f <-- fA d = 0.023069ms 
bfsgputdcsc_sc::time time bfs functions d = 0.347126ms 
bfsgputdcsc_sc::average time BFS d = 0.370195ms 

check sigma in CSC(sc) format: values of the GPU computed sigma vector are correct 

check values of S_hgpu: values of the GPU computed S vector are correct 

visited vertices == 9

S   S_hgpu 
0,0,0
1,1,1
2,2,2
3,1,1
4,1,1
5,2,2
6,2,2
7,1,1
8,2,2

sigma   sigma_hgpu 
0,1.000000,1.000000
1,1.000000,1.000000
2,2.000000,2.000000
3,1.000000,1.000000
4,1.000000,1.000000
5,3.000000,3.000000
6,3.000000,3.000000
7,1.000000,1.000000
8,2.000000,2.000000

scan=0.000s,degree_t= 0.000s,transf_format_t=0.000s,bfs_td_seq_t=0.000s

**Comment by iosmers** [comment]
thanks for help, I will check my GPU

**Comment by iosmers** [comment]
Hi, the reason why my GPU does't work is that the Makefile configure `-arch=sm_61`, that configure does't work on Tesla k40c. I change it '-arch=sm_35' and it computes the expected result.  Thanks for help.
